BEGIN
EXECUTE IMMEDIATE 'DROP TABLE surveys';
EXECUTE IMMEDIATE 'DROP TABLE tasks';
EXECUTE IMMEDIATE 'DROP TABLE lee_jobs';
EXECUTE IMMEDIATE 'DROP TABLE persons';
END;
/
show errors

CREATE TABLE persons
(
  person_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  person_last_name VARCHAR2(50) NOT NULL,
  person_first_name VARCHAR2(50) NOT NULL,
  person_status VARCHAR2(50),
  person_email VARCHAR2(50),
  person_pw VARCHAR2(15),
  person_task NUMBER,
  CONSTRAINT persons_person_id_pk PRIMARY KEY (person_id)
  );

CREATE TABLE tasks
(
    task_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    task_name VARCHAR2(50) NOT NULL,
    task_supervisor VARCHAR2(50) NOT NULL,
    CONSTRAINT tasks_task_id_pk PRIMARY KEY (task_id)
);

CREATE TABLE surveys
(
  question_id NUMBER CONSTRAINT surveys_question_id_pk PRIMARY KEY,
  question_text VARCHAR2(1000) NOT NULL,
  question_answer_yes NUMBER,
  question_answer_no NUMBER,
  question_answer_not_sure NUMBER,
  question_admin_id NUMBER NOT NULL,
  CONSTRAINT surveys_question_admin_id_fk FOREIGN KEY (question_admin_id) REFERENCES persons(person_id)
);

CREATE TABLE LEE_JOBS (JOB_ID NUMBER PRIMARY KEY ,
JOB_TYPE VARCHAR2 (15) NOT NULL,
JOB_TITLE VARCHAR2 (30) NOT NULL, 
JOB_INFO VARCHAR2 (2000) NOT NULL,
JOB_START_DATE DATE NOT NULL,
JOB_END_DATE DATE,
JOB_LOCATION VARCHAR2 (20)NOT NULL,
JOB_SALARY NUMBER(9,2)NOT NULL,
JOB_PERSON_ID NUMBER REFERENCES PERSONS (PERSON_ID)
);

INSERT INTO persons VALUES (73, 'Durant', 'Kevin', 'survey_admin', 'kd@gmail.com', '12345', null);
INSERT INTO persons VALUES (1, 'Franco', 'James', 'patient', 'jf@gmail.com', '55555', null);

INSERT INTO surveys VALUES (0, 'Does our service good?', 3, 1, 1, 73);
INSERT INTO surveys VALUES (1, 'Is it easy to find our place?', 5, 0, 0, 73);
INSERT INTO surveys VALUES (2, 'Is is easy to connect with your doctor?', 2, 2, 1, 73);

quit
