n01257490/oracle@humber_db

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE persons';
EXECUTE IMMEDIATE 'DROP TABLE surveys';

END;
/
show errors

CREATE TABLE persons
(
  person_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  person_last_name VARCHAR2(50) NOT NULL,
  person_first_name VARCHAR2(50) NOT NULL,
  person_status VARCHAR2(15),
  person_pw VARCHAR2(15),
  CONSTRAINT persons_person_id_pk PRIMARY KEY (person_id)
  );

CREATE TABLE surveys
(
  question_id NUMBER CONSTRAINT surveys_question_id_pk PRIMARY KEY,
  question_text VARCHAR2(1000) NOT NULL,
  question_answer_yes NUMBER,
  question_answer_no NUMBER,
  question_answer_not_sure NUMBER,
  question_admin_id NUMBER NOT NULL,
  CONSTRAINT surveys_question_admin_id_fk FOREIGN KEY (question_admin_id) REFERENCES persons(person_id)
);

INSERT INTO persons VALUES (73, 'Durant', 'Kevin', 'survey_admin', '12345');

INSERT INTO surveys VALUES (0, 'Does our service good?', 3, 1, 1, 73);
INSERT INTO surveys VALUES (1, 'Is it easy to find our place?', 5, 0, 0, 73);
INSERT INTO surveys VALUES (2, 'IS is easy to connect with your doctor?', 2, 2, 1, 73);

quit
